apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec: 
  parentRefs:
  - kind: Gateway
    name: external-http
    namespace: gateway
  hostnames:
  - "argocd.brotherscloud.online"
  rules:
  - matches:
    - path:
        value: /*
    backendRefs:
    - name: argocd-server
      port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-healthcheck
  namespace: argocd
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 80
        portName: http
        requestPath: /
     # httpsHealthCheck:
      #  port: 8443
      #  requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
